### ISSUE TITLE
  BlockCommands problem

### ISSUE THREAD

**Issue by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [cnaude/MuteManager#12]
the plugin lets use commands if a player is muted: 
![image](https://user-images.githubusercontent.com/100978781/176738122-669fe2f5-d948-41cf-925d-ff494e51b4db.png)
![image](https://user-images.githubusercontent.com/100978781/176738190-3089052e-0cd7-456a-a26d-a10fcf703a23.png)
![image](https://user-images.githubusercontent.com/100978781/176738250-7ee1ca57-dbdc-473c-9543-77cd8a16ab60.png)

**Comment by cnaude** [comment]
I just tested this with MC 1.19 and it appears to work correctly. Can you do me a favor and set "Debug: true" in your MuteManager config.yml? Then test the /msg command again? It will print a few helpful messages in the console log.

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment]
> I just tested this with MC 1.19 and it appears to work correctly. Can you do me a favor and set "Debug: true" in your MuteManager config.yml? Then test the /msg command again? It will print a few helpful messages in the console log.
 WAIT
 
 so it does block only commands from Commands ? thank you, will test right now :D

**Comment by cnaude** [comment]
Please try this latest build. It has the lowest possible priority for the command listener. It might be able to catch the /w before the other plugins catches it.
https://jenkins.chrisnaude.com/jenkins/job/MuteManager/lastSuccessfulBuild/artifact/target/MuteManager-0.16-67.jar
