### ISSUE TITLE
Internal Error Occurred when muting a player

### ISSUE THREAD

**Issue by palmerjj01** [cnaude/MuteManager#3]
I am trying to permanently mute a player on my server, however when I do this, I get an internal error occurred and the message below in the console. This link also shows my config: http://pastebin.com/2egq11Cr

21.11 21:35:27 [Server] INFO ... 15 more
21.11 21:35:27 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at com.cnaude.mutemanager.MuteCommand.onCommand(MuteCommand.java:125) ~[?:?]
21.11 21:35:27 [Server] INFO at com.cnaude.mutemanager.MuteManager.mutePlayer(MuteManager.java:110) ~[?:?]
21.11 21:35:27 [Server] INFO at com.cnaude.mutemanager.MuteManager.adjustMuteDuration(MuteManager.java:95) ~[?:?]
21.11 21:35:27 [Server] INFO Caused by: java.lang.NullPointerException
21.11 21:35:27 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
21.11 21:35:27 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
21.11 21:35:27 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-06ad352-4a7472d]
21.11 21:35:27 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mute' in plugin MuteManager v0.16-34

**Comment by cnaude** [comment]
I need to see the full stack trace. Are you running this command from the game or console?

**Comment by palmerjj01** [comment]
I am running it in-game. Should I run it in debug mode and paste what it gives then?

**Comment by cnaude** [comment]
Yes that would be useful. And also more of the strack trace if possible.

**Comment by palmerjj01** [comment]
It appears I am getting less, and what is even stranger is it is unmuting players who are not muted 

22.11 18:15:11 [Server] INFO [DEBUG] Unmuting: ConfusedSheep
22.11 18:15:10 [Server] INFO [DEBUG] Unmuting: Itz_YoshiYT
22.11 18:15:10 [Server] INFO [DEBUG] Unmuting: ConfusedSheep
22.11 18:15:08 [Server] INFO [DEBUG] Checking mute list.
22.11 18:15:06 [Server] INFO [DEBUG] Unmuting: ConfusedSheep
22.11 18:14:59 [Server] INFO ... 8 more
22.11 18:14:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-06ad352-4a7472d]
22.11 18:14:59 [Server] INFO at com.cnaude.mutemanager.MuteCommand.onCommand(MuteCommand.java:125) ~[?:?]
22.11 18:14:59 [Server] INFO at com.cnaude.mutemanager.MuteManager.mutePlayer(MuteManager.java:110) ~[?:?]
22.11 18:14:59 [Server] INFO at com.cnaude.mutemanager.MuteManager.adjustMuteDuration(MuteManager.java:95) ~[?:?]
22.11 18:14:59 [Server] INFO Caused by: java.lang.NullPointerException
22.11 18:14:59 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
22.11 18:14:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-06ad352-4a7472d]
22.11 18:14:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-06ad352-4a7472d]
22.11 18:14:59 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-06ad352-4a7472d]
22.11 18:14:59 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot.jar:git-Spigot-06ad352-4a7472d]
22.11 18:14:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-06ad352-4a7472d]
22.11 18:14:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-06ad352-4a7472d]
22.11 18:14:59 [Server] INFO at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
22.11 18:14:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-06ad352-4a7472d]
22.11 18:14:59 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mute' in plugin MuteManager v0.16-34
22.11 18:14:59 [Server] WARN Unexpected exception while parsing console command "mute WitheredBonnieYT perm Bullying and Caps. Appeal at blockworldmc.enjin.com/appeal"

**Comment by cnaude** [comment]
What version of PerWorldPlugins are you running? I believe the error is coming from that plugin.

**Comment by palmerjj01** [comment]
R: PerWorldPlugins v1.2.5 for 1.8.1

**Comment by cnaude** [comment]
That's the same version I tested as well. You will want to send that stack trace to the PerWorldPlugins developer. The NPE is happening at "me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) "
I don't think there is anything I can do from the MuteManager side to resolve that.

**Comment by palmerjj01** [comment]
It seems that the PerWorldPlugins page has no ticket button, or at least not that I can find

**Comment by palmerjj01** [comment]
This is really strange, but the error fixed itself somehow, closing this issue.

**Comment by cnaude** [comment]
Glad to hear that. I was never able to reproduce the error.
