### ISSUE TITLE
Bug Report (Plugin Disables Itself Upon Relog (1.8.8 Spigot))

### ISSUE THREAD

**Issue by Betterjakers** [cnaude/MuteManager#4]
BUG REPORT

Hello! I am using the Dev-Build v0.16-40. For some reason, the plugin does not work after I relog. Yes, it works the first time I load it - it works like it should. Then, when I relog, the plugin breaks. I type "/Mute Betterjakers 1m Test", but that does not work. I get no feedback in chat, just nothing happens. My console shows nothing except: "betterjakers issued server command: /mute betterjakers"

**Comment by cnaude** [comment]
Hi, please enable debug mode and provide any debug output from the console when this issue occurs.

**Comment by Betterjakers** [comment]
Hello! Here is the paste bin: http://pastebin.com/Y5NHNkkb

What I did (That should be shown in the paste bin) was /Reload the server, then I typed /Mute betterjakers 1. That worked. I then left and rejoined, and tried the command again, and nothing happened.

**Comment by cnaude** [comment]
Can you do a complete stop and start of the server? You should never use the /reload command. That breaks a lot of plugins.

**Comment by Betterjakers** [comment]
I have attempted removing and reinstalling the plugin, but the same thing happens. In fact, now on the first load up the commands do not work.

**Comment by cnaude** [comment]
Are you using a plugin manager to remove and install the plugin? Any errors when the plugin loads?

**Comment by Betterjakers** [comment]
No, I am not using any plugin installer/remover. I tried it with a plugin installer/remover with the bukkit page version, but that version did not work. I then downloaded and put the plugin directly in the plugins folder (After deleting the previous MuteManager jar and file).

I do not see any errors with the plugin. Here is the start-up console: http://pastebin.com/a5X70RB1
Here is when I log in and run "/Mute Betterjakers 1": http://pastebin.com/VYt3LvmH

**Comment by cnaude** [comment]
I have been unable to replicate this problem. I believe the issue is with your server or another plugin interfering. What is your plugin list?

**Comment by Betterjakers** [comment]
My plugin list: https://gyazo.com/50e059510b080e6db4f51f5fcf1d1e5f

**Comment by cnaude** [comment]
Does the mute command work from the console? What happens when you type "/help MuteManager" ?

**Comment by Betterjakers** [comment]
Hello! It seems odd, but it fixed itself. The error no longer happens. I will contact you if it happens again.

**Comment by cnaude** [comment]
Okay.
