### ISSUE TITLE
Unable to Mute not Displaying (Spigot 1.9)

### ISSUE THREAD

**Issue by KingYoshiYT** [cnaude/MuteManager#5]
Hello,

I am currently using MuteManager for 1.9, I attempted to mute an OP, but it no UnableToMute error in chat. In the console it said: Player KingYoshiYT is exempt due to mutemanager.muteexempt. however still, nothing was shown in chat.

Have I done something wrong or is this an error?

**Comment by cnaude** [comment]
Remove the permission node mutemanager.muteexempt from the person you are trying mute.

**Comment by KingYoshiYT** [comment]
That isn't the issue, I was just wondering why I see no error in chat when trying to mute someone with that node

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/MuteManager/44/

**Comment by KingYoshiYT** [comment]
Yes, this works, thank you
