### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by OrlandoLaCrue** [cnaude/MuteManager#7]
I hate having to decide how long to mute a player. So I have come up with this idea.
A feature where the player gets longer mutes as he or she gets muted more often.
Example:
**1 Mute** = 10 minutes
**2 Mutes** = 20 minutes
**3 Mutes** = 30 minutes
**4 Mutes** = 40 minutes
**5 Mutes** = 50 minutes
And so on..
And for the users who does like this idea or likes to decide how long to mute a player, there would be a feature in the config to turn this feature on/off.
Config Example:
**TimeMutes:** true
OR
**TimeMutes:** false

And when Timed mutes are on, the self timing is disabled. So instead of **/mute (player) (minutes) (reason)** it would be **/mute (player) (reason).** Because Time mutes are on.

Thanks.
  Orlando

**Comment by emrebenuzunolan** [comment]
This idea is awesome.
